# Generated by Django 2.2.7 on 2019-12-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(4, '最近评论'), (3, '最热文章'), (1, 'HTML'), (2, '最新文章')], default=1, verbose_name='展示类型'),
        ),
    ]
